- hosts: localhost
  connection: local
  
  tasks:

  # Example  - Executes the ./scripts/orgs/import_sites.py -f vars/sites.csv --org_id=e92db139-f481-4e64-a674-2d521d106894 --google_api_key=AIzaSyC1qzntcGzye0UZ9amxxGQfAoq2kRcqdX8
  - name: Execute Python Script locally
    ansible.builtin.script:
      cmd: /home/administrator/scripts/orgs/import_sites.py -f /home/administrator/scripts/vars/sites.csv -e /home/administrator/.mist_env --org_id=e92db139-f481-4e64-a674-2d521d106894 --google_api_key=AIzaSyC1qzntcGzye0UZ9amxxGQfAoq2kRcqdX8 --org_name=Demo-lab
      executable: /usr/bin/python3

    register: result

  - ansible.builtin.debug:
      msg: "{{ result }}"